/**
 * Airport Surfaces Types
 *
 * Types for the airport pavement data extracted from X-Plane apt.dat.
 * This data includes taxiway and apron polygons for terrain flattening.
 *
 * Data source: X-Plane apt.dat (GNU GPL licensed)
 * Generated by: scripts/shipping/data-generation/extract-airport-surfaces.py
 *
 * @see scripts/shipping/data-generation/extract-airport-surfaces.py for extraction details
 */

/**
 * Surface type codes (abbreviated for file size)
 *
 * Single character representing the pavement surface type:
 * - 'a' = asphalt
 * - 'c' = concrete
 * - 'g' = grass
 * - 'd' = dirt
 * - 'r' = gravel (previously 'g' which conflicted, using 'r' for "rough")
 * - 'l' = lakebed
 * - 'w' = water
 * - 'n' = snow
 * - 'o' = other
 */
export type SurfaceTypeCode = 'a' | 'c' | 'g' | 'd' | 'r' | 'l' | 'w' | 'n' | 'o'

/**
 * Map surface type code to full surface type name
 */
export const SURFACE_TYPE_NAMES: Record<SurfaceTypeCode, string> = {
  a: 'asphalt',
  c: 'concrete',
  g: 'grass',
  d: 'dirt',
  r: 'gravel',
  l: 'lakebed',
  w: 'water',
  n: 'snow',
  o: 'other',
}

/**
 * Pavement polygon from X-Plane apt.dat
 *
 * Uses abbreviated field names to reduce file size:
 * - s = surface type
 * - v = vertices
 * - h = holes (optional)
 */
export interface AptDatPavement {
  /** Surface type (single character code) */
  s: SurfaceTypeCode
  /** Outer boundary vertices as [longitude, latitude][] */
  v: [number, number][]
  /** Optional holes (cutouts) as arrays of [longitude, latitude][] */
  h?: [number, number][][]
}

/**
 * Airport data from X-Plane apt.dat
 *
 * Uses abbreviated field names:
 * - n = name
 * - e = elevation (feet)
 * - p = pavements
 */
export interface AptDatAirport {
  /** Airport name */
  n: string
  /** Airport elevation in feet MSL */
  e: number
  /** Pavement polygons (taxiways, aprons) */
  p: AptDatPavement[]
}

/**
 * Metadata from the airport surfaces file
 */
export interface AirportSurfacesMeta {
  /** File format version */
  version: number
  /** ISO timestamp when the file was generated */
  generated: string
  /** Data source (e.g., "X-Plane apt.dat") */
  source: string
  /** Number of airports in the file */
  airport_count: number
  /** Total number of pavement polygons */
  total_pavements: number
  /** License information */
  license: string
}

/**
 * Root structure of the airport-surfaces.json.gz file
 */
export interface AirportSurfacesData {
  /** File metadata */
  _meta: AirportSurfacesMeta
  /** Airport data indexed by ICAO code */
  airports: Record<string, AptDatAirport>
}
